#############################################################################
# Makefile for building: final_project
# Generated by qmake (3.1) (Qt 6.2.4)
# Project:  final_project.pro
# Template: subdirs
# Command: C:\Qt\6.2.4\mingw_64\bin\qmake.exe -o Makefile final_project.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = C:\Qt\6.2.4\mingw_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\6.2.4\mingw_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\6.2.4\mingw_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-search_engine \
		sub-tests


sub-search_engine-qmake_all:  FORCE
	@if not exist search_engine\ mkdir search_engine\ & if not exist search_engine\ exit 1
	cd search_engine\ && $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\search_engine\search_engine.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd search_engine\ && $(MAKE) -f Makefile qmake_all
sub-search_engine: FORCE
	@if not exist search_engine\ mkdir search_engine\ & if not exist search_engine\ exit 1
	cd search_engine\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\search_engine\search_engine.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-search_engine-make_first: FORCE
	@if not exist search_engine\ mkdir search_engine\ & if not exist search_engine\ exit 1
	cd search_engine\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\search_engine\search_engine.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-search_engine-all: FORCE
	@if not exist search_engine\ mkdir search_engine\ & if not exist search_engine\ exit 1
	cd search_engine\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\search_engine\search_engine.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-search_engine-clean: FORCE
	@if not exist search_engine\ mkdir search_engine\ & if not exist search_engine\ exit 1
	cd search_engine\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\search_engine\search_engine.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-search_engine-distclean: FORCE
	@if not exist search_engine\ mkdir search_engine\ & if not exist search_engine\ exit 1
	cd search_engine\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\search_engine\search_engine.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-search_engine-install_subtargets: FORCE
	@if not exist search_engine\ mkdir search_engine\ & if not exist search_engine\ exit 1
	cd search_engine\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\search_engine\search_engine.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-search_engine-uninstall_subtargets: FORCE
	@if not exist search_engine\ mkdir search_engine\ & if not exist search_engine\ exit 1
	cd search_engine\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\search_engine\search_engine.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-tests-qmake_all:  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd tests\ && $(MAKE) -f Makefile qmake_all
sub-tests: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-tests-make_first: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-tests-all: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-tests-clean: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-tests-distclean: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-tests-install_subtargets: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-tests-uninstall_subtargets: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: final_project.pro C:/Qt/6.2.4/mingw_64/mkspecs/win32-g++/qmake.conf C:/Qt/6.2.4/mingw_64/mkspecs/features/spec_pre.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/device_config.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/common/sanitize.conf \
		C:/Qt/6.2.4/mingw_64/mkspecs/common/gcc-base.conf \
		C:/Qt/6.2.4/mingw_64/mkspecs/common/g++-base.conf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/common/windows-vulkan.conf \
		C:/Qt/6.2.4/mingw_64/mkspecs/common/g++-win32.conf \
		C:/Qt/6.2.4/mingw_64/mkspecs/common/windows-desktop.conf \
		C:/Qt/6.2.4/mingw_64/mkspecs/qconfig.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_ext_freetype.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_ext_libpng.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3danimation.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dcore.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dextras.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dinput.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dlogic.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquick.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3drender.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3drender_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_activeqt.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_activeqt_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_axserver.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_charts.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_charts_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_chartsqml.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_chartsqml_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_core5compat.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_core5compat_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_datavisualization.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_dbus.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_dbus_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_entrypoint_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labsanimation.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labssettings.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_linguist.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_linguist_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_multimedia.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_networkauth.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_positioningquick.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlcore.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmltest.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3d.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3deffects.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dparticles.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quicktimeline.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_repparser.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_repparser_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_scxml.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_scxml_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_scxmlqml.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_sensors.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_sensorsquick.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_serialbus.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_shadertools.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_shadertools_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_statemachine.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_statemachine_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_statemachineqml.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_tools_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_uiplugin.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_webchannel.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_websockets.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_websockets_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_webview.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_webview_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_webviewquick.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_webviewquick_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_zlib_private.pri \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/qt_functions.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/qt_config.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/win32-g++/qmake.conf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/exclusive_builds.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/toolchain.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/default_pre.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/win32/default_pre.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/resolve_config.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/default_post.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/qml_debug.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/entrypoint.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/precompile_header.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/warn_on.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/qmake_use.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/file_copies.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/win32/windows.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/testcase_targets.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/exceptions.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/yacc.prf \
		C:/Qt/6.2.4/mingw_64/mkspecs/features/lex.prf \
		final_project.pro
	$(QMAKE) -o Makefile final_project.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
C:/Qt/6.2.4/mingw_64/mkspecs/features/spec_pre.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/device_config.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/common/sanitize.conf:
C:/Qt/6.2.4/mingw_64/mkspecs/common/gcc-base.conf:
C:/Qt/6.2.4/mingw_64/mkspecs/common/g++-base.conf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/common/windows-vulkan.conf:
C:/Qt/6.2.4/mingw_64/mkspecs/common/g++-win32.conf:
C:/Qt/6.2.4/mingw_64/mkspecs/common/windows-desktop.conf:
C:/Qt/6.2.4/mingw_64/mkspecs/qconfig.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_ext_freetype.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_ext_libpng.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3danimation.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3danimation_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dcore.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dcore_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dextras.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dextras_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dinput.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dinput_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dlogic.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquick.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquick_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickextras.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickinput.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickrender.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3drender.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_3drender_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_activeqt.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_activeqt_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_axbase_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_axcontainer.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_axserver.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_axserver_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_bluetooth.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_charts.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_charts_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_chartsqml.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_chartsqml_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_concurrent.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_concurrent_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_core.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_core5compat.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_core5compat_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_core_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_datavisualization.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_dbus.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_dbus_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_designer.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_designer_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_entrypoint_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_fb_support_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_gui.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_gui_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_help.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_help_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labsanimation.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labssettings.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labssettings_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labssharedimage.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_linguist.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_linguist_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_multimedia.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_multimedia_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_multimediaquick_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_network.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_network_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_networkauth.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_networkauth_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_nfc.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_nfc_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_opengl.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_opengl_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_openglwidgets.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_positioning.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_positioning_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_positioningquick.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_printsupport.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_printsupport_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qml.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qml_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlcore.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlcore_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmldom_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlmodels.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmltest.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmltest_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3d.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3d_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dassetutils.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3deffects.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3deffects_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dhelpers.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3diblbaker.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dparticles.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dutils.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quick_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickdialogs2.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quicklayouts.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quicktimeline.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quicktimeline_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickwidgets.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_remoteobjects.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_repparser.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_repparser_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_scxml.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_scxml_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_scxmlqml.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_scxmlqml_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_sensors.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_sensors_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_sensorsquick.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_sensorsquick_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_serialbus.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_serialbus_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_serialport.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_serialport_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_shadertools.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_shadertools_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_sql.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_sql_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_statemachine.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_statemachine_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_statemachineqml.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_statemachineqml_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_svg.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_svg_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_svgwidgets.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_testlib.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_testlib_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_tools_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_uiplugin.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_uitools.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_uitools_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_webchannel.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_webchannel_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_websockets.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_websockets_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_webview.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_webview_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_webviewquick.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_webviewquick_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_widgets.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_widgets_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_xml.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_xml_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/modules/qt_lib_zlib_private.pri:
C:/Qt/6.2.4/mingw_64/mkspecs/features/qt_functions.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/qt_config.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/win32-g++/qmake.conf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/spec_post.prf:
.qmake.stash:
C:/Qt/6.2.4/mingw_64/mkspecs/features/exclusive_builds.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/toolchain.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/default_pre.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/win32/default_pre.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/resolve_config.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/exclusive_builds_post.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/default_post.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/qml_debug.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/entrypoint.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/precompile_header.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/warn_on.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/qmake_use.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/file_copies.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/win32/windows.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/testcase_targets.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/exceptions.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/yacc.prf:
C:/Qt/6.2.4/mingw_64/mkspecs/features/lex.prf:
final_project.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile final_project.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-search_engine-qmake_all sub-tests-qmake_all FORCE

make_first: sub-search_engine-make_first sub-tests-make_first  FORCE
all: sub-search_engine-all sub-tests-all  FORCE
clean: sub-search_engine-clean sub-tests-clean  FORCE
distclean: sub-search_engine-distclean sub-tests-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-search_engine-install_subtargets sub-tests-install_subtargets FORCE
uninstall_subtargets: sub-search_engine-uninstall_subtargets sub-tests-uninstall_subtargets FORCE

sub-search_engine-debug:
	@if not exist search_engine\ mkdir search_engine\ & if not exist search_engine\ exit 1
	cd search_engine\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\search_engine\search_engine.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-tests-debug:
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-search_engine-debug sub-tests-debug

sub-search_engine-release:
	@if not exist search_engine\ mkdir search_engine\ & if not exist search_engine\ exit 1
	cd search_engine\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\search_engine\search_engine.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-tests-release:
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-search_engine-release sub-tests-release

sub-search_engine-check:
	@if not exist search_engine\ mkdir search_engine\ & if not exist search_engine\ exit 1
	cd search_engine\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\search_engine\search_engine.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-tests-check:
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-search_engine-check sub-tests-check

sub-search_engine-benchmark:
	@if not exist search_engine\ mkdir search_engine\ & if not exist search_engine\ exit 1
	cd search_engine\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\search_engine\search_engine.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-tests-benchmark:
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\study\Modul_40\my_project\final_project\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-search_engine-benchmark sub-tests-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

